#if !canImport(ObjectiveC)
import XCTest

extension DateCalcTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateCalcTests = [
        ("DateCalcTests", DateCalcTests),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DateCalcTests.__allTests__DateCalcTests),
    ]
}
#endif
