name: Build Linux

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Linux framework
        run: |
          swift build
          swift test --enable-test-discovery
